name: Angular Build and Test

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Export Chrome Binary
        run: export ${{ format('CHROME_BINARY={1} >> {2}', steps.setup-chrome.outputs.chrome-path, $GITHUB_ENV) }}
      - name: Test
        run: npm test
